name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.repository == 'tatzeroko/language-tools'
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    env:
      NPM_CONFIG_PROVENANCE: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          publish: pnpm changeset:publish
          commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
